apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: smsv1b8os-python
  janus-idp.io/tekton: smsv1b8os-python
  backstage.io/kubernetes-id: smsv1b8os-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: smsv1b8os-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
