apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: smsv1b8os-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: smsv1b8os-python 
  name: smsv1b8os-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: smsv1b8os-python 
