apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: smsv1b8os-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:78f5ef1be288bba46fea90da59f80d3008c4690e@sha256:ae3365eb7823f5ee13237a4f7b6bca0710a0e0dd096e9dece6c3da8d3cb677e8
          name: container-image
